### ISSUE TITLE
ATECC608A replies with ATCA_RX_NO_RESPONSE on CryptoAuth Xplained Pro Version B

### ISSUE THREAD

**Issue by mka-3s** [MicrochipTech/cryptoauthlib#107]
Hi,

I am using a CryptoAuth Xplained Pro Version B board to test the ATECC608A device, but I have run into some issues. 
Both atcab_init and atcab_random returns ATCA_RX_NO_RESPONSE when communicating with the 608A on address 0xC0.
However, if I try to communicate with the ATAES132A on address 0xA0 then the two functions return ATCA_WAKE_FAILED. 

The board is connected through I2C to an embedded linux platform. 
My test code is as follows:

```
#include <stdio.h>
#include "cryptoauthlib.h"


int main(int argc, char const *argv[])
{
    ATCAIfaceCfg linux_i2c;
    uint8_t num = 0;
    
    linux_i2c.iface_type = ATCA_I2C_IFACE;
    linux_i2c.devtype = ATECC608A;
    linux_i2c.atcai2c.slave_address = 0xa0;
    linux_i2c.atcai2c.bus = 1;
    linux_i2c.atcai2c.baud = 400000;
    linux_i2c.wake_delay = 1500;
    linux_i2c.rx_retries = 20;

    ATCA_STATUS status = atcab_init(&linux_i2c);
    printf("init status: %d\r\n", status);

    status = atcab_random(&num);
    printf("status: %d, ranNum: %u\r\n", status, num);

    return 0;
}
```

I have used a scope to verify that the bus has communication on it.

Any suggestions to why the communication fails?

Best regards
Martin

**Comment by mka-1** [comment]
I found the issue. If anyone else have the same issue, then it was because I did not wake up the device before I requested the random number.
