### ISSUE TITLE
atca_mbedtls_cert_add fails with buffer space too small

### ISSUE THREAD

**Issue by anozaki** [MicrochipTech/cryptoauthlib#109]
`atca_mbedtls_cert_add` is calling `atcacert_read_cert` without setting `cert_len` causing errors in some cases.

`atcacert_read_cert` returns the byte written in `cert_len` but also expect the buffer size to be set in `cert_len` when calling.

**Comment by zynaptic** [comment]
This is the simple fix I've been using:
https://github.com/zynaptic/cryptoauthlib/commit/7890b443296586c4102fd2ce9df8cf05cf791ab3
I don't seem to be able to raise a PR for it (possibly don't have the required permissions), but it's a trivial change.

**Comment by bryan-hunt** [comment]
Just cleaning up old issues - This was fixed in v3.2.1
