### ISSUE TITLE
atcab_read_enc issue

### ISSUE THREAD

**Issue by agilesai1294** [MicrochipTech/cryptoauthlib#126]
Hi, I have a question regarding atcab_read_enc() function. i have slot 5 which is configured to do encrypted read and encrypted write. when i try to do atcab_read_enc(5,0,read_data,IOKEY,6) it gives me an error of 0xF4. Can you help me resolve this issue ASAP?
![image](https://user-images.githubusercontent.com/34946584/71023322-7f584880-20d0-11ea-93f8-285be476a489.png)

Steps i followed:

ENC_KEY = bytearray([

  0x37, 0x80, 0xe6, 0x3d, 0x49, 0x68, 0xad, 0xe5,

  0xd8, 0x22, 0xc0, 0x13, 0xfc, 0xc3, 0x23, 0x84,

  0x5d, 0x1b, 0x56, 0x9f, 0xe7, 0x05, 0xb6, 0x00,

  0x06, 0xfe, 0xec, 0x14, 0x5a, 0x0d, 0xb1, 0xe3

])

write_key_slot = config.SlotConfig[5].WriteKey

print(write_key_slot) # prints 6

write_data = bytearray(32)

read_data = bytearray(32)

assert atcab_write_zone(2, write_key_slot, 0, 0, ENC_KEY, 32) == ATCA_SUCCESS

assert atcab_random(write_data) == ATCA_SUCCESS

assert atcab_write_enc(5, 0, write_data, ENC_KEY, write_key_slot) == ATCA_SUCCESS

assert atcab_read_enc(5, 0, read_data, ENC_KEY, write_key_slot) == ATCA_SUCCESS #Throws an error 244 which is 0xF4

**Comment by agilesai1294** [comment]
Changing the read key slot from 15 to 6 worked.

**Comment by dogusural** [comment]
Hey agilesai1294 , 

Can you tell me where you found the GUI to configure the atecc device ? 

Best

**Comment by bryan-hunt** [comment]
@dogusural For product support questions you should submit a product support request through the [Microchip Support portal](https://microchipsupport.force.com/s/). We are unable to provide the same level of product usage support via github as we do through the support portal.

For details on the Support Portal or how to use it please see [How to Submit a Case](https://microchipsupport.force.com/s/article/How-to-submit-a-case)
