### ISSUE TITLE
python info.py with hid not working

### ISSUE THREAD

**Issue by agilesai1294** [MicrochipTech/cryptoauthlib#128]
Hi,

I have tried out a sample code to test ATECC608A.
from cryptoauthlib import *
def info(iface='i2c', device='ecc', **kwargs):
    ATCA_SUCCESS = 0x00
    load_cryptoauthlib()
    cfg = cfg_ateccx08a_kithid_default()
    cfg.iface_type = ATCAIfaceType.ATCA_I2C_IFACE
    cfg.devtype=ATCADeviceType.ATECC608A
    cfg.cfg.atcahid.dev_interface=ATCAKitType.ATCA_KIT_I2C_IFACE
    cfg.cfg.atcahid.dev_identity=0xC0
    print('0x{:08X}'.format(cfg.cfg.atcahid.dev_identity))
    atcab_init(cfg)
    info = bytearray(4)
    assert atcab_info(info) == ATCA_SUCCESS
    print('\nDevice Part:')
    print('    ' + get_device_name(info))
   serial_number = bytearray(9)
    print('0x{:08X}'.format(atcab_read_serial_number(serial_number)))
    atcab_release()

The output of the following program is:
![image](https://user-images.githubusercontent.com/34946584/72097966-864b3300-32eb-11ea-92dc-54bdde28accb.png)

Can you tell me what am i doing wrong?

**Comment by bryan-hunt** [comment]
It looks like you didn't compile HID support when you built the library.

**Comment by agilesai1294** [comment]
@bryan-hunt I am using the following code on Jupyter notebook and i installed cryptoauthlib using the following command: pip install cryptoauthlib>=20191112
Let me know if I had to do something to get this working

**Comment by agilesai1294** [comment]
@bryan-hunt I was able to resolve that. Now when I try to initialize I get this error.

![image](https://user-images.githubusercontent.com/34946584/72156845-81868d80-3384-11ea-8f76-9a980754ff33.png)

Cryptoauthlib failed with error 0xE5( ATCA_RX_CRC_ERROR)
