### ISSUE TITLE
ATECC608A - AES/SHA - KeyType

### ISSUE THREAD

**Issue by shinigami35** [MicrochipTech/cryptoauthlib#129]
Hello Everyone,

I use the Atecc608a for my own project and I would like to use the AES-128 and SHA  function before sending my data (node). 
In my case, I cannot use the AES-128 function with a private key in a slot. For slot 1-10 (include) my Key Configuration is '0x33 0x00' for each keys and for the other key, the configuration is '0x1C 0x00'.
I see in this github that new types of key have been added to the Atecc608a, SHA type (0x07) and AES type (0x06). So I guess in the KeyConfig (0-15 bit for each slot), I have to set the byte 13 14 15 with the new type of key.
- So for SHA type, the bit 13, 14 and 15 to 1
- So for AES type, the bit 13 and 14 to 1, and 15 to 0
Am I right ?

Could someone explain what configuration I have to put to use SHA with one slot and AES with an other ?

_PS_ : Sorry for my english, the language is not my main.

Best regards,
Adrien

**Comment by bryan-hunt** [comment]
For product support you should  talk to your assigned FAE or submit a request through the mySupport portal on [microchip.com](http://www.microchip.com/support/hottopics.aspx). 

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchip.secure.force.com/microchipknowledge/articles/en_US/FAQ/How-to-submit-a-case)
