### ISSUE TITLE
[Question] ATECC608 Complete Data Sheet

### ISSUE THREAD

**Issue by pstolarz** [MicrochipTech/cryptoauthlib#134]
I've general question related to ATECC608A detailed technical specification. Is there ATECC608A Complete Datasheet available as it was for ATECC508A? I've tried hard to find something more detailed related to this new chip (especially its new features comparing to 508) but wasn't able to. AN2589 (Differences Between the ATECC608A and ATECC508A) is not sufficient for me.

**Comment by bryan-hunt** [comment]
Per the statement in the [summary datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/ATECC608A-CryptoAuthentication-Device-Summary-Data-Sheet-DS40001977B.pdf) you need to contact your local sales for a full copy. The end off the datasheet also lists those region offices.

You can also submit a product support request through the mySupport portal on [microchip.com](http://www.microchip.com/support/hottopics.aspx). 

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchip.secure.force.com/microchipknowledge/articles/en_US/FAQ/How-to-submit-a-case)

**Comment by pstolarz** [comment]
Thanks
