### ISSUE TITLE
PKCS#11 token initialization error

### ISSUE THREAD

**Issue by Anabel-Dev** [MicrochipTech/cryptoauthlib#141]
Greetings of the day!

We are using ATECC608A chip to encrypt a folder via pkcs11-helper. At some point, we are trying to initialize the token but it remains uninitialized and we also dont know the user pin. Only the token info and the slot info are available. Can you help us initialize the token?

$ pkcs11-tool --module=/usr/lib/libcryptoauth.so -L
Available slots:
Slot 0 (0x0): 0_3_0
  token state:   uninitialized

$ pkcs11-tool --module=/usr/lib/libcryptoauth.so -I
Cryptoki version 2.40
Manufacturer     Microchip Technology Inc v
Library          Cryptoauthlib PKCS11 Interface (ver 3.2)
Using slot 0 with a present token (0x0)

**Comment by Anabel-Dev** [comment]
Hello
To initialize the token you need to lock the data zone in the cryptochip(ATECC608A). Then initialize the token using pkcs11-tool. If you are getting the CANT_LOCK error, then set the flag.

**Comment by SimoneBongini** [comment]
hello @Anabel-Dev, how can I lock the data zone in the cryptochip?

**Comment by Anabel-Dev** [comment]
Hi Simone,

Once you lock the data zone, there's no unlock command or go back.

Please check with the cryptochip technical team for more info

Thanks,
Anabel
