### ISSUE TITLE
Golang PKCS#11 library fails to load libcryptoauth.so due to its MaxSession limitation

### ISSUE THREAD

**Issue by r-funke** [MicrochipTech/cryptoauthlib#150]
The golang package `github.com/ThalesIgnite/crypto11` has a hard requirement that `MaxRwSessionCount` must be `>=2`, so it can open at least two sessions. A [comment in the source code](https://github.com/ThalesIgnite/crypto11/blob/85520c03f33551fcc6eae7dfd240dbc7cb1e9bbc/crypto11.go#L327) says that it uses one keepalive session plus a pool of on-demand worker sessions. 

Cryptoauthlib has `ulMaxSessionCount` and `ulMaxRwSessionCount` set to 1, [see here](https://github.com/MicrochipTech/cryptoauthlib/blob/2df0eb145c7241263d07577394dd12f8b1e783f0/lib/pkcs11/pkcs11_token.c#L366). 

As a quick&dirty workaround I can change the cryptoauthlib and set `ulMaxRwSessionCount=2`. Then the golang crypto11 library is able to load libcryptoauth.so and query slots. But I'm not sure if that can have any negative side effects.

Unfortunately, `github.com/ThalesIgnite/crypto11` is the only PKCS#11 libraray available for golang.

**Comment by bryan-hunt** [comment]
Yes that was to work around some other implementations. It is actually supposed to be set to PKCS11_MAX_SESSIONS_ALLOWED but this was a work-around for some client applications that seemed to misbehave. I have not revisited it to determine why problems were occuring.

see [pkcs11_config.h](https://github.com/MicrochipTech/cryptoauthlib/blob/2df0eb145c7241263d07577394dd12f8b1e783f0/lib/pkcs11/pkcs11_config.h#L89..L91)
