### ISSUE TITLE
Compressed Certificate Definition is incomplete

### ISSUE THREAD

**Issue by DurandA** [MicrochipTech/cryptoauthlib#153]
The [Compressed Certificate Definition AN_8974](https://www.microchip.com/wwwAppNotes/AppNotes.aspx?appnote=en591852) describes a compressed certificate format that can be reconstructed into full X.509 certificates.

I believe that this definition is incomplete as I can't find some mandatory elements of the X.509 certificate. The [Table 3-1. Signer Certificate Location] and [Table 3-2. Device Certificate Location] describes the location of the certificate component. However, there is no mention of the Subject field in the device certificate and the Issuer field in the Signer certificate (which are mandatory for X.509).

Can you clarify how these fields are reconstructed?

I can't find references to the Issuer Name nor the Subject Name of the certificate in the C lib. E.g., in the python tests in [`test_atcacert_round_trip_qa()`](https://github.com/MicrochipTech/cryptoauthlib/blob/master/python/tests/test_atcacert.py) a certificate is created by calling `create_device_cert()` and provisioned on the device. This certificate contains an Issuer Name and a Subject Name with both Common Name and Organization attributes. See the picture below as I generated the same certificate.

![certificate](https://user-images.githubusercontent.com/3709037/80958286-0baba380-8e05-11ea-802e-027ce5870412.png)

I see no references to these fields in any of the certificate templates from CryptoAuthLib. Are these _Additional custom certificate elements_ from atcacert?

https://github.com/MicrochipTech/cryptoauthlib/blob/102d7fcfa2cc1671fddb814bf8079756f70f7109/lib/atcacert/atcacert_def.c#L633-L659

**Comment by bryan-hunt** [comment]
Those elements are considered static data with the exception of the signer id. When the certificate chain is created for a product line the organization name obviously will not change - what changes is the specific signing HSM which is denoted by the signer id code. 

For further assistance on this topic you have to submit a request through [Microchip Support](https://microchipsupport.force.com/s/). For details on the mySupport Portal or how to use it please see [How to submit a case](https://microchipsupport.force.com/s/article/How-to-submit-a-case)
