### ISSUE TITLE
HAL support for SAME54

### ISSUE THREAD

**Issue by jasmineymlo** [MicrochipTech/cryptoauthlib#154]
I have an IAR workbench project targeting SAME54 Xpro running and working.  Now that I want to plug in the TrustFlex (ECC608A) with the mikroBUS adaptor, but HAL for E54 is not in the repo.  Would this be added anytime soon?

I have used Harmony3 to generate the HAL, but that cannot be easily integrated to my current IAR project.  Is there instruction on how to do so?  Thanks.

**Comment by bryan-hunt** [comment]
The SAME54 is supported through Harmony 3 (like all 32bit Microchip MCUs) so a specific SAME54 hal will not be added. The SAME54 was also never supported in ASF3 so even in the old Atmel toolchain there would not be a specific HAL for the SAME54. The SAME54 is only supported in Atmel START and Harmony 3. 

If you used START to generate your IAR project then you can use the start hal.

You can submit a product support request through the mySupport portal on [microchip.com](http://www.microchip.com/support/hottopics.aspx) and request support MCU32 support as this is related to toolchains and MCU drivers

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchip.secure.force.com/microchipknowledge/articles/en_US/FAQ/How-to-submit-a-case)
