### ISSUE TITLE
Simplify hal abstraction!?

### ISSUE THREAD

**Issue by 5frank** [MicrochipTech/cryptoauthlib#156]
I was happy to find this library and appreciate the initiative!  I'm currently trying to port this to mynewt. It looks like requirements for hal support have grown over time and created some messy code!?

Example the callstack for sending data
1. `atca_iface.c:atsend()` wrapper that calls `ca_iface->atsend`
 
2. `ca_iface->atsend` function pointer in struct atca_iface typedef ATCAIface in atca_iface.h, calls `hal->halsend`

3. `hal->halsend()` (function pointer of ATCAHAL_t struct from hal/atca_hal.h)
    calls any of the following.
    `hal->halsend = &hal_i2c_send;`
    `hal->halsend = &hal_swi_send;`
    `hal->halsend = &hal_kit_cdc_send;`
    `hal->halsend = &hal_kit_hid_send;`
    `hal->halsend = cfg->atcacustom.halsend;`

From what I can tell, higher layers of this lib do not need to have any knowledge of transport used? So why not keep it simple with a single header with function definitions that the hal port  layer implements? (could use weak declarations for non required hal functions such as lock/unlock).

I guess one should not fix what is not broken, but ...
- this is seems unnecessarily hard to maintain and port
- fixes and improvements is less likely to get back to this repo if adopting it to new environments requires modifications to original source. 

Apologies if I'm just complaining!

**Comment by bryan-hunt** [comment]
v3.2.0 has been released. In your case I think you'll be most interested in the behind the scenes function hal_iface_register_hal as you can manually attach HALs without having to use any of the ATCA_HAL_* definitions.
