### ISSUE TITLE
Provisioning Server

### ISSUE THREAD

**Issue by j4cbo** [MicrochipTech/cryptoauthlib#158]
Is the source for the AT88CKECCPROVISION provisioning server (SecureProvisioningServerSetup_1.0.1.exe at https://www.microchip.com/swlibraryweb/product.aspx?product=cryptoauthprovision) available, or is there an equivalent provisioning server implementation somewhere?

**Comment by bryan-hunt** [comment]
You can make that request by submiting a product support request through the mySupport portal on [microchip.com](http://www.microchip.com/support/hottopics.aspx).

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchip.secure.force.com/microchipknowledge/articles/en_US/FAQ/How-to-submit-a-case)
