### ISSUE TITLE
Specifing I2C address with HID interface does not work with DM320118

### ISSUE THREAD

**Issue by bse-sja** [MicrochipTech/cryptoauthlib#183]
Setting cfg.atcahid.dev_identity to anything but zero does not work with DM320118.

DM320118 returns ID string of "ECC608A" while code is looking for "ECC608" so
(strcmp(device_match, dev_type) fails in lib/hal/kit_protocol.c.

**Comment by drewwestrick** [comment]
Looks like a typo in the code. If you change the source code from ECC608 to ECC608A does it solve the problem?

**Comment by bryan-hunt** [comment]
This should have been resolved in v3.2.3
