### ISSUE TITLE
Compiling with gcc10 fails due to -fno-common being the default

### ISSUE THREAD

**Issue by kraj** [MicrochipTech/cryptoauthlib#185]
gcc10 has changed defaults to use -fno-common and this fails badly during compile since the code is not clean for -fno-common to work. A workaround is to use -fcommon option explicitly on compiler cmdline.

**Comment by bryan-hunt** [comment]
Ah yes this appears to be a bug in the multi platform static/dynamic header definitions.

**Comment by bryan-hunt** [comment]
@kraj This should be resolved in v3.2.4
