### ISSUE TITLE
SHA256 HMAC with 64 Byte Key on ATECC608a

### ISSUE THREAD

**Issue by Einhornhool** [MicrochipTech/cryptoauthlib#186]
Hello,
I'm trying to generate a SHA256 HMAC digest with a 64 Byte key on the 608a. Even though I can store 64 Bytes in the TempKey register, the command seems to use only 32 Bytes and I haven't found an option to change this, yet.

Is there a possibility to use a larger key and if so, how can I use it?

**Comment by bryan-hunt** [comment]
This is covered by the datasheet under the section 11.18: HMAC_Start

For product support questions you should submit a product support request through the [Microchip Support portal](https://microchipsupport.force.com/s/). We only provide library usage support on github.

For details on the Support Portal or how to use it please see [How to Submit a Case](https://microchipsupport.force.com/s/article/How-to-submit-a-case)
