### ISSUE TITLE
Question: How to build on windows?

### ISSUE THREAD

**Issue by minghuadev** [MicrochipTech/cryptoauthlib#187]
Hi, I want to add an I2C interface through a buspirate dongle. On Linux, the library can be built using "python setup.py install" to build and install, or using "python setup.py build_ext" to build only. How that can be done on a windows machine? 

Thanks.

**Comment by bryan-hunt** [comment]
The same way. You'll need something that cmake can detect however without passing in a bunch of arguments - generally that means having MSVC installed.

**Comment by minghuadev** [comment]
Thanks. I'm wishing that a gcc can do the work.

**Comment by bryan-hunt** [comment]
@minghuadev you'll have to identify the toolchain information to CMake. If you're using the gui it'll have a prompt when you run configure for what generator to use. If you running from the command line you'll have to manually specify the generator if CMake can't identify a toolchain. For example to use gcc as part of mingw (the common way) you can run cmake from mingw or specify `-G "MinGW Makefiles"` with your CMake call.
