### ISSUE TITLE
cmake fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by bse-sja** [MicrochipTech/cryptoauthlib#197]
v3.2.4 fails on Ubuntu 18.04 and cmake 3.10.2 ( v3.2.3 works with ubuntu 18.04 with v3.2.3 and v3.2.4 works with ubuntu 20.04):

cmake .

CMake Error at lib/CMakeLists.txt:329 (install):
  install TARGETS given unknown argument "NAMELINK_COMPONENT".

**Comment by bryan-hunt** [comment]
I'll add a check to not set up that component for cmake versions older than 3.12

**Comment by bryan-hunt** [comment]
This should be resolved in v3.2.5
