### ISSUE TITLE
atcacert_read_cert() the 416 byte "data" array looks like it should be outside the loop

### ISSUE THREAD

**Issue by umanayana** [MicrochipTech/cryptoauthlib#20]
In file "atcacert_client.c" at line 88. It looks like the array of 416 bytes should be outside the loop, because every time the loop run the variable is re-declared. I am guessing since you're not clearing the variable to zero i.e uint8_t data[416] = { 0 }; The data stay on the stack and you are not seeing an issue. 
If the intention is to keep the data within the array then it should be initialise external to the loop and cleared to zero uint8_t data[416] = { 0 }
 
Also why is it 416 byte required?

**Original Code**

```
for (i = 0; i < device_locs_count; i++)
    {
        uint8_t data[416];
        if (device_locs[i].zone == DEVZONE_DATA && device_locs[i].is_genkey)
        {
            ret = atcab_get_pubkey(device_locs[i].slot, data);
            if (ret != ATCA_SUCCESS)
            {
                return ret;
            }
        }
        else
        {
            size_t start_block = device_locs[i].offset / 32;
            uint8_t block;
            size_t end_block = (device_locs[i].offset + device_locs[i].count) / 32;
            for (block = (uint8_t)start_block; block < end_block; block++)
            {
                ret = atcab_read_zone(device_locs[i].zone, device_locs[i].slot, block, 0, &data[block * 32 - device_locs[i].offset], 32);
                if (ret != ATCA_SUCCESS)
                {
                    return ret;
                }
            }
        }

        ret = atcacert_cert_build_process(&build_state, &device_locs[i], data);
        if( ret != ATMEL_SUCCESS )
        {
            return ret;
        }
    }
````

**Comment by BenUdall-Microchip** [comment]
data is temporary buffer used to stored data read from the CryptoAuth device, with 416 bytes being the largest continuous block of memory one can read (slot 8 size). The variable is not used before being read into, so static initialization isn't required. Without static initialization to consider, it's declared in the smallest scope required.
