### ISSUE TITLE
please give a demo how to create  ssl socket via openssl where openssl engine is used.

### ISSUE THREAD

**Issue by zyfromsh** [MicrochipTech/cryptoauthlib#202]
I am eager to know how to create a ssl client socket via pkcs11 openssl engine .but after went through this project, I failed to find what I want

**Comment by bryan-hunt** [comment]
Openssl documentation is handled by the Openssl project. You can look at the hostapd and curl projects for examples outside of the openssl documentation for engine instantiation.
