### ISSUE TITLE
Error in pkcs11_init:1439: PKCS #11 error

### ISSUE THREAD

**Issue by pavithran93** [MicrochipTech/cryptoauthlib#205]
I followed the steps in 
https://github.com/MicrochipTech/cryptoauthlib/wiki/PKCS11-Linux-Setup. 

When I run p11tool --list-all I am receiving below response
![Capture](https://user-images.githubusercontent.com/76467218/105567848-082fc200-5d70-11eb-8b7f-358ce490a37a.PNG)

When I run p11tool --list-all --provider /usr/lib/libcryptoauth.so I getting this response
![Capture](https://user-images.githubusercontent.com/76467218/105567872-344b4300-5d70-11eb-9724-3564e185e4cc.PNG)

What's the difference between these two commands. Why my outcome is different?

Next I am trying to initialize the chip using the command p11tool --initialize "pkcs11:serial=10A592C2E036" --label appzgate. I am getting the error 
Error in pkcs11_init:1439: PKCS #11 error.
![Capture](https://user-images.githubusercontent.com/76467218/105567930-b50a3f00-5d70-11eb-83a4-6bae42e8b03d.PNG)

As per the tutorial I am following it supposed to initialize the chip. But I am getting the error.

My requirement is I have SD card having Raspberry Pi OS. I have encrypted the root patriation of my SD card using LUKS encryption, to decrypt back I have generated the key file on USB stick and added the key file to LUKS patriation,  when the raspberry pi rebooted the system will read the key from associated USB stick using that key file the SD card will be unlocked and boot up. Due to the USB stick is not secure to store the key file, I trying to store the key file on ATECC608A and read the key file from ATECC608A on boot

 Please assist me to resolve this to proceed further

**Comment by bryan-hunt** [comment]
So the issue I'm seeing from the above are as follows

1) use the latest release that has been published - in your case to minimize changes use tag 20210121 which is the most recent python version - this will help if you need to run python scripts to verify anything

2) You are seeing the two tokens because your p11-kit set up is allowing for it. You can modify your p11-kit configuration from merge to only which instead of merging the module configuration from root with the module configuration in your user directory it will instead only use the user configuration.

3) You are seeing a private and public key from the device - this is an indication that the device is configured and locked already. Trying to initialize an already initialized device will fail.

**Comment by pavithran93** [comment]
Hi bryan,
             Thanks for your reply
             After I restart the device. I can initialize the token
![Capture](https://user-images.githubusercontent.com/76467218/105953484-36820a00-60ae-11eb-83bc-ae05078cb6dd.PNG)
            
              Once I initialize the totally showing three objects. Weather can I remove the key after initialization?
              
              Weather I can generate the LUKS key file in the device ATECC608A. Can access that key at initramfs window?

**Comment by pavithran93** [comment]
![Capture](https://user-images.githubusercontent.com/76467218/105956048-28ce8380-60b2-11eb-946f-edf5d9f3954b.PNG)

You check the above picture. 
1) I am generating key file in the pen drive
2) Adding that key file from pen drive to my LUKS encrypted patrician
3) Referring the pen drive UUID  to cryptab for auto unlock the SD card

I am trying to do similar things with ATECC608A. Because storing the key file in pen drive is not safer

**Comment by pavithran93** [comment]
Hi Bryan,
               I successfully initialized and verified the certificate.
               I need to know how to add keys to ATECC608A.
               How to get back stored keys.
               How to lock the ATECC608A corresponding to hardware (Raspberry Pi). By this we will ensure the ATECC608A should work only on specific hardware device.
               Please assist me on this.

**Comment by pavithran93** [comment]
Thank you.
                 Issue got solved
