### ISSUE TITLE
`atca_mbedtls_eckey_t` not defined

### ISSUE THREAD

**Issue by fstephany** [MicrochipTech/cryptoauthlib#206]
Compilation fails when using mbedTLS and `MBEDTLS_ECDSA_SIGN_ALT` is set.

The struct `atca_mbedtls_eckey_t` is defined within `#ifndef MBEDTLS_ECDSA_SIGN_ALT` in `atca_mbedtls_wrap.c` ([line 858](https://github.com/MicrochipTech/cryptoauthlib/blob/8c29897017ae08f85178d79f39a62bf0e3febe88/lib/mbedtls/atca_mbedtls_wrap.c#L858)) but is used outside any define guards later at [line 1097](https://github.com/MicrochipTech/cryptoauthlib/blob/8c29897017ae08f85178d79f39a62bf0e3febe88/lib/mbedtls/atca_mbedtls_wrap.c#L1097).

Shouldn't the struct be defined right before the `ifndef` ?

**Comment by bryan-hunt** [comment]
v3.3.1 is now released. In order to address all combinations of _ALT options this was moved into the header.
