### ISSUE TITLE
In library.py a fixed path seperator is used

### ISSUE THREAD

**Issue by timonehr** [MicrochipTech/cryptoauthlib#209]
Hey everyone,

when i imported the cryptoauthlib module the python command `subprocess`  was not able to run programs from `/usr/bin`. 

I started to debug my code, because before we updated to the latest version everything was fine.

During the debugging i found a bug in the `library.py`. In this line is `;` used, as the path seperator.

The path result in the python environment was:
`'PATH': '/usr/lib/python3.8/site-packages/cryptoauthlib;/usr/bin:/bin'`

https://github.com/MicrochipTech/cryptoauthlib/blob/51fa84248e47e90792231aef691c1a1584ba1076/python/cryptoauthlib/library.py#L81

It should use the python method `os.pathsep`. In this way it is system independent.

`os.environ['PATH'] = os.path.dirname(__file__) + os.pathsep + os.environ['PATH']`

**Comment by bryan-hunt** [comment]
v3.3.1 is now released
