### ISSUE TITLE
ATCA_HAL_LEGACY_API support life?

### ISSUE THREAD

**Issue by deangereaux** [MicrochipTech/cryptoauthlib#210]
How long will the ATCA_HAL_LEGACY_API be supported?

**Comment by bryan-hunt** [comment]
There isn't a firm date for when it will be deprecated - but as long as the library comes with HALs that required it then it will be supported. If I were to hazard a guess it will be about a year. I makes a lot of sense to move to the new API however as it moves all of the device logic into the library and keeps it out of the HAL itself.

**Comment by deangereaux** [comment]
Thanks for the info.
