### ISSUE TITLE
3.3.1 Release does not build with PKCS11 enabled

### ISSUE THREAD

**Issue by tanstafel** [MicrochipTech/cryptoauthlib#221]
Building the 3.3.1 release fails in the pkcs11 code:

$ cmake -DATCA_PKCS11:BOOL=ON CMakeLists.txt
$ make

Building C object lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_key.c.o
../../lib/pkcs11/pkcs11_key.c: In function 'pkcs11_key_write'
../../lib/pkcs11/pkcs11_key.c:728:18:error: 'cfg_ptr' undeclared (first use in this function)
  728 |             if ((cfg_ptr->SlotConfig[obj_ptr->slot] & ATCA_SLOT_CONFIG_IS_SECRET_MASK) &&
      |                  ^~~~~~~
../../lib/pkcs11/pkcs11_key.c:728:18:note: each undeclared identifier is reported only once for each function it appears in
../../lib/pkcs11/pkcs11_key.c:1017:18:error: invalid storage class for function 'pkcs11_key_derive_ca'
 1017 |     static CK_RV pkcs11_key_derive_ca(pkcs11_session_ctx_ptr pSession, pkcs11_object_ptr pBaseKey, pkcs11_object_ptr pSecretKey, CK_ECDH1_DERIVE_PARAMS_PTR pEcdhParameters)
      |                  ^~~~~~~~~~~~~~~~~~~~
../../lib/pkcs11/pkcs11_key.c:1224:5:error: expected declaration or statement at end of input
 1224 |     }
      |     ^
make[2]: *** [lib/CMakeFiles/cryptoauth.dir/build.make:1096: lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_key.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 44%] Building C object lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_cert.c.o
[ 52%] Building C object lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_os.c.o
[ 49%] Building C object lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_init.c.o
[ 51%] Building C object lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_object.c.o
../../lib/pkcs11/pkcs11_object.c: In function 'pkcs11_object_create'
../../lib/pkcs11/pkcs11_object.c:494:90:error: expected ')' before ';' token
  494 |                     (void)pkcs11_config_remove_object ((pLibCtx, pSession->slot, pObject);
      |                                                                                          ^
      |                                                                                          )
../../lib/pkcs11/pkcs11_object.c:494:80:warning: passing argument 1 of 'pkcs11_config_remove_object' from incompatible pointer type [-Wincompatible-pointer-types]
  494 |                     (void)pkcs11_config_remove_object ((pLibCtx, pSession->slot, pObject);
      |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
      |                                                                                |
      |                                                                                pkcs11_object_ptr
In file included from ../../lib/pkcs11/pkcs11_object.c:30:
./pkcs11_config.h:132:54:note: expected 'pkcs11_lib_ctx_ptr' but argument is of type 'pkcs11_object_ptr'
  132 | CK_RV pkcs11_config_remove_object(pkcs11_lib_ctx_ptr pLibCtx, pkcs11_slot_ctx_ptr pSlot, pkcs11_object_ptr pObject);
      |                                   ~~~~~~~~~~~~~~~~~~~^~~~~~~
../../lib/pkcs11/pkcs11_object.c:494:27:error: too few arguments to function 'pkcs11_config_remove_object'
  494 |                     (void)pkcs11_config_remove_object ((pLibCtx, pSession->slot, pObject);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../lib/pkcs11/pkcs11_object.c:30:
./pkcs11_config.h:132:7:note: declared here
  132 | CK_RV pkcs11_config_remove_object(pkcs11_lib_ctx_ptr pLibCtx, pkcs11_slot_ctx_ptr pSlot, pkcs11_object_ptr pObject);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../../lib/pkcs11/pkcs11_object.c:494:91:error: expected ';' before '}' token
  494 |                     (void)pkcs11_config_remove_object ((pLibCtx, pSession->slot, pObject);
      |                                                                                           ^
      |                                                                                           ;
  495 |                                                        }
      |                                                        ~                                   
make[2]: *** [lib/CMakeFiles/cryptoauth.dir/build.make:1135: lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_object.c.o] Error 1
[ 50%] Building C object lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_mech.c.o
[ 53%] Building C object lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_signature.c.o
../../lib/pkcs11/pkcs11_signature.c: In function 'pkcs11_signature_verify'
../../lib/pkcs11/pkcs11_signature.c:265:5:error: 'pConfig' undeclared (first use in this function)
  265 |     pConfig = (atecc508a_config_t*)pKey->config;
      |     ^~~~~~~
../../lib/pkcs11/pkcs11_signature.c:265:5:note: each undeclared identifier is reported only once for each function it appears in
../../lib/pkcs11/pkcs11_signature.c:281:30:error: 'status' undeclared (first use in this function)
  281 |         if (ATCA_SUCCESS == (status = atcab_sha_hmac(pData, ulDataLen, pKey->slot, buf, SHA_MODE_TARGET_OUT_ONLY)))
      |                              ^~~~~~
../../lib/pkcs11/pkcs11_signature.c:285:17:error: 'verified' undeclared (first use in this function)
  285 |                 verified = TRUE;
      |                 ^~~~~~~~
make[2]: *** [lib/CMakeFiles/cryptoauth.dir/build.make:1174: lib/CMakeFiles/cryptoauth.dir/pkcs11/pkcs11_signature.c.o] Error 1

Looking at the code it looks like incomplete refactoring. One would assume that before releasing code (or even merging any new commits) a build is executed for common configurations?! PKCS11 is not that uncommon I think...

**Comment by bryan-hunt** [comment]
The merge error has been corrected - the tag has been updated
