### ISSUE TITLE
pkcs11_key_get_ec_point broken in 3.3.x

### ISSUE THREAD

**Issue by tanstafel** [MicrochipTech/cryptoauthlib#222]
pkcs11_key_get_ec_point() is broken in 3.3.x release. libp11 calls this first with pAttribute->pValue == NULL to determine the length of the returned EC_POINT attribute. Now this just returns CKR_ARGUMENTS_BAD. In that case pkcs11_attrib_fill() should still be called.

**Comment by bryan-hunt** [comment]
Should be resolved in v3.3.2
