### ISSUE TITLE
Missing newline at the end of file in most (all?) files

### ISSUE THREAD

**Issue by akindestam** [MicrochipTech/cryptoauthlib#228]
The C standard specifies that files must end with a newline. A last line without a newline is undefined behavior.

More practically, a lot of C compilers either print a warning/error or fail if the last line is not a newline.

**Comment by akindestam** [comment]
We currently have to patch cryptoauthlib for this to make it compile on TI ARM C compiler, when using cryptoauthlib under TI RTOS.

**Comment by bryan-hunt** [comment]
Should be resolved in v3.3.2
