### ISSUE TITLE
AssertionError while writing secret key on slot 5

### ISSUE THREAD

**Issue by pavithran93** [MicrochipTech/cryptoauthlib#229]
Hi,
        I am trying to write secret key in slot 5  using cryptoauthlib python library, I am getting assertion error. But I can successfully generate private key on slot 0, 2, 3 and 4.
        For AES encryption I need to store the secret key under slot 5 or slot 9. But I could not write the keys. Please help me to resolve this.
        
![image](https://user-images.githubusercontent.com/76467218/120314752-2608c700-c30e-11eb-90a2-885f14b13f55.png)

      As mentioned in Microchip Datasheet I am using Write Data Zone Encryption method
      
![image](https://user-images.githubusercontent.com/76467218/120314926-5b151980-c30e-11eb-9fa4-2ac47af8b339.png)

![image](https://user-images.githubusercontent.com/76467218/120315010-741dca80-c30e-11eb-9a67-583d3dfbdc88.png)

        My Refernce: I used your reference from test_jwt.py under python folder
        
![image](https://user-images.githubusercontent.com/76467218/120315095-8c8de500-c30e-11eb-93bf-475440b9deb3.png)

       My Code in python
![image](https://user-images.githubusercontent.com/76467218/120315236-b21aee80-c30e-11eb-995b-c5a1e42e164e.png)

       Any help to generate secret key on slot 5 is appreciated

**Comment by pavithran93** [comment]
Solved this by changing cfg_ateccx08a_kitcdc_default() to cfg_ateccx08a_i2c_default().
Now I can connect with the ATECC608A  chip.

Another question. When I request public key from the slot 0 using 
assert ATCA_SUCCESS == atcab_get_pubkey(0, publickey)
print('Public Key')
print(''.join(['%02X ' % x for x in publickey]))
print(publickey)

I am getting 64 bit byte array as below

![py1](https://user-images.githubusercontent.com/76467218/120261639-e371cb00-c2ca-11eb-8da1-6866f0ac02c3.PNG)

How I can convert to public key file like below?

![py2](https://user-images.githubusercontent.com/76467218/120261706-08fed480-c2cb-11eb-9895-ce4bfaefff9f.PNG)

**Comment by bryan-hunt** [comment]
For product support please submit a request through the [mySupport portal](https://microchipsupport.force.com/s/) where Microchip's global team of FAEs can work on your use case and questions.

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case)
