### ISSUE TITLE
Incorrect wake data byte

### ISSUE THREAD

**Issue by deangereaux** [MicrochipTech/cryptoauthlib#232]
**Describe the bug**
This looks like a bug, in calib_wakeup_i2c(), calib_basic.c, the data byte is set to 1 by this line:  `uint8_t second_byte = 0x01`.  Shouldn't this be '0'?   0x1 is the sleep command.  Yes sending 0x01 at 100000kbps works to wake up the device because of the slower baud rate, but I think this leads to confusion.

**To Reproduce**

**Expected behavior**
I would expect the wake data byte to be zero.

**Comment by bryan-hunt** [comment]
No this is correct. The address being written to is 00 not the device address. The address 00 is called a general call. The write to address 00 triggers the wake for the device. The cryptoauth parts do not support the general call and will not ack it. The second byte will only get transmitted if there is another device on the bus that does support the general call and acks it - in that case this second byte has the least significant bit set to not produce undesirable behavior in the device that acked the general call (when the least significant bit is cleared it indicates an I2C address write to the device responding to the general call).

See the [I2C specification](https://www.nxp.com/docs/en/user-guide/UM10204.pdf) section 3.1.13
