### ISSUE TITLE
Hardware Abstraction Harmony

### ISSUE THREAD

**Issue by gskrish7** [MicrochipTech/cryptoauthlib#244]
I am not sure this would a feature request or improvement request.

While I am trying to directly utilize the hal layer, found `"harmony/src/hal_i2c_harmony.h"`; function `hal_i2c_init` takes `ATCAIfaceCfg` pointer to configuration. The configuration has I2C slave details like 
1. Slave Address
2. Bus Number
3. Wakeup Delay
4. Baud rate(in MHz)

I understand, hal_i2c_harmony interfaces cryptoauthlib with sercom2 driver. This hal has to take care of 
1. Shifting address while read & write operations with retries.
2. Verify status of bus before read/write using sercom driver.
3. And others essential tasks that eases the user job, 

But the functions `hal_i2c_wake`, `hal_i2c_idle`, `hal_i2c_send`, `hal_i2c_receive`, `hal_i2c_sleep`, and `hal_i2c_release` has parameter of type `ATCAIface` as argument. Is that providing  `ATCAIfaceCfg` as argument not sufficient. Could we keep the HAL layer simple, could it be having standard data type rather than using ATCA types?

Thanks,

**Comment by bryan-hunt** [comment]
This is a HAL for support cryptoauth devices in the Harmony 3 environment. As such it is not intended to support use cases that are not using a cryptoauth device. You use the I2C_Drv component or the plib directly.

Architectural notes for the HAL

a) There are many architectures that are supported by Harmony - these architectures are very different in terms of initialization and use. The existing configuration structure is insufficient to determine that and the HAL would become extremely complicated - however the harmony configurator has all of the data required to produce a structure that reference the correct harmony plib functions. This structure is what the harmony hal is using.
b) wake/idle/sleep functions are all obsolete and are part of the core library now.
c) The hal interface is generating and intended to be portable - there is simply no way of getting around the need to carry quite a bit of context around.
