### ISSUE TITLE
How to select specific secure element on DM320118.

### ISSUE THREAD

**Issue by gantzm** [MicrochipTech/cryptoauthlib#247]
I have a DM320118 evaluation board connected and running with cryptoauthlib via the hid interface.  It's my understanding from the docs that there are three 608 devices on this board.  How do I select which one I'm interacting with when I call:

`atcab_init(&cfg_ateccx08a_kithid_default);`

I've tried different settings for:

`
cfg_ateccx08a_kithid_default.atcahid.dev_identity
cfg_ateccx08a_kithid_default.atcahid.idx
`

and some others.  But the library always seems to talk to the same chip ( determined by getting sn ) or just errors out on the init call.

**Comment by PhillyNJ** [comment]
You need to change the address in the library. The addresses are documented in the schematics. 

https://ww1.microchip.com/downloads/en/DeviceDoc/DM320118_Rev6_schematics.PDF

Regards,

Phil

**Comment by KalyanCManukonda** [comment]
As Phil rightly mentioned we need to select the device and its interface to get a targeted communication. Following python  script should help you understand it better.

``` python
import cryptoauthlib as cal


cfg = cal.iface._iface_load_default_config('cfg_ateccx08a_kithid_default')
cfg.cfg.atcahid.dev_interface = cal.ATCAKitType.ATCA_KIT_I2C_IFACE

# Default device addresses
#           Trust&GO device address = 0x6A,
#           TrustFLEX device address = 0x6C and
#           TrustCUSTOM device address = 0xC0
cfg.cfg.atcahid.dev_identity = 0x6A

assert cal.atcab_init(cfg) == cal.Status.ATCA_SUCCESS, 'Can\'t connect to device'
serial_num = bytearray(9)
assert cal.atcab_read_serial_number(serial_num) == cal.Status.ATCA_SUCCESS, 'Reading Serial Number'
print(f'Device Serial Number is: {serial_num.hex().upper()}')
```

**Comment by gantzm** [comment]
Yes, it turns out ( after looking through the source code ) that the filters are an all or nothing proposition.  I was attempting to just use the I2C address.  Changing my code to the following fixed the problem:

`
cfg_ateccx08a_kithid_default.atcahid.dev_interface = ATCA_KIT_I2C_IFACE;
cfg_ateccx08a_kithid_default.devtype = ATECC608B;
cfg_ateccx08a_kithid_default.atcahid.dev_identity = 0x6C;

`
