### ISSUE TITLE
Porting on freeRTOS

### ISSUE THREAD

**Issue by Nc3491** [MicrochipTech/cryptoauthlib#253]
The project README says that he library is structured to support portability to:

   -> multiple hardware/microcontroller platforms
    -> multiple environments including bare-metal, RTOS and Windows/Linux/MacOS

I am trying to port in to freeRTOS, how to proceed with it?

For product support please submit a request through the [mySupport portal](https://microchipsupport.force.com/s/) where Microchip's global team of FAEs can work on your use case and questions.

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case)

**Comment by bryan-hunt** [comment]
This question doesn't have enough detail to answer reasonably. FreeRTOS does not define a hardware api so your porting exercise will revolve around porting the hardware interface.

The easiest way to get started is to use a Microchip development board with the Harmony 3 system.

Regardless if you need additional support and training materials you should use the above links to the Microchip support portal.
