### ISSUE TITLE
pkcs11 branch not support ATECC608B

### ISSUE THREAD

**Issue by smartdabao** [MicrochipTech/cryptoauthlib#256]
Hi all,
    I saw ATECC608B support not listed in pkcs11 branch, not listed in main branch. So I can not use pkcs11 with ATECC608B, is it right? Or I missed something?

    Any help?

**Comment by bryan-hunt** [comment]
The main branch has full pkcs11 support. There is no distinction between A/B devices as far as device communication is concerned so you don't need to specify A/B in the device type.

**Comment by smartdabao** [comment]
Good, thank you very much.
