### ISSUE TITLE
atcab_verify_stored_mac with KeyConfig.ReqRandom

### ISSUE THREAD

**Issue by IDS-MK** [MicrochipTech/cryptoauthlib#276]
I am trying to use atcab_verify_stored_mac API but 
but only get calib_verify.c:111:f4:calib_verify - execution failed

atcab_verify_stored did work before locking the data zone

the slot15 is the public key and is already validated by parent key in slot 13

we want uses secureboot command but that does fail also with same error

the spec states at the verify command

Regardless of the mode, if the public key is stored within an EEPROM slot and If KeyConfig.ReqRandom is set for that slot, then the value in TempKey must have been generated using the random number generator within ATECC608A. The Message Digest Buffer may not be used for the message in this case.

from the source code i can see that calib_verify_extern_stored_mac does use the  Message Digest Buffer is this the root cause of the error? 

below is the configuration 

Device Part:
    ATECC608

Serial number:
    01,0x23,0xF4,0x47,0x1F,0x8B,0x64,0xC5,0xEE

Configuration Zone:
    01,0x23,0xF4,0x47,0x00,0x00,0x60,0x02,0x1F,0x8B,0x64,0xC5,0xEE,0x01,0x45,0x00
    C0,0x00,0x00,0x00,0x83,0x20,0x83,0x20,0x87,0x20,0xC5,0x46,0xD5,0x46,0xC6,0x26
    C5,0x25,0xC5,0x26,0xC5,0x46,0xC5,0x46,0xD5,0x46,0xD5,0x46,0x83,0x20,0x86,0x85
    C5,0x26,0x9D,0x16,0xFF,0xFF,0xFF,0xFF,0x00,0x00,0x00,0x00,0xFF,0xFF,0xFF,0xFF
    00,0x00,0x00,0x00,0x00,0x00,0x19,0xFE,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
    00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x1F,0x5F,0x07,0x75,0x00,0x00,0x00,0x00
    33,0x10,0x33,0x10,0x33,0x10,0x38,0x10,0x3C,0x10,0x78,0x00,0x78,0x00,0x38,0x00
    38,0x10,0x38,0x10,0x3C,0x10,0x3C,0x10,0x33,0x10,0x70,0x00,0x1C,0x00,0x72,0x00

Check Device Locks
    Config Zone is locked
    Data Zone is locked
    0 Slot is unlocked
    1 Slot is unlocked
    2 Slot is unlocked
    3 Slot is unlocked
    4 Slot is unlocked
    5 Slot is locked
    6 Slot is locked
    7 Slot is locked
    8 Slot is unlocked
    9 Slot is unlocked
    10 Slot is unlocked
    11 Slot is unlocked
    12 Slot is unlocked
    13 Slot is locked
    14 Slot is unlocked
    15 Slot is locked

**Comment by bryan-hunt** [comment]
You need to submit your request through the [mySupport portal](https://microchipsupport.force.com/s/)

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case)
