### ISSUE TITLE
v3.3.3: pkcs11: cannot load Private Key from engine

### ISSUE THREAD

**Issue by ambarus** [MicrochipTech/cryptoauthlib#278]
**Describe the bug**
`$ p11tool --list-all
warning: no token URL was provided for this operation; the available tokens are:

pkcs11:model=p11-kit-trust;manufacturer=PKCS%2311%20Kit;serial=1;token=System%20Trust
pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=237C30CB6AC65A01;token=00ABC
$ p11tool --initialize "pkcs11:serial=237C30CB6AC65A01" --label greengrass
Enter Security Officer's PIN: 
Initializing token... done

Token was successfully initialized; use --initialize-pin and --initialize-so-pin to set or reset PINs
$ p11tool --list-all pkcs11:token=00ABC
Object 0:
	URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=237C30CB6AC65A01;token=00ABC;object=device;type=private
	Type: Private key (EC/ECDSA-SECP256R1)
	Label: device
	Flags: CKA_PRIVATE; CKA_SENSITIVE; 
	ID: 

Object 1:
	URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=237C30CB6AC65A01;token=00ABC;object=device;type=public
	Type: Public key (EC/ECDSA-SECP256R1)
	Label: device
	ID: 

Object 2:
	URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=237C30CB6AC65A01;token=00ABC;object=device;type=cert
	Type: X.509 Certificate
	Label: device
	ID: 

Object 3:
	URL: pkcs11:model=ATECC608A;manufacturer=Microchip%20Technology%20Inc;serial=237C30CB6AC65A01;token=00ABC;object=signer;type=cert
	Type: X.509 Certificate
	Label: signer
	Flags: CKA_CERTIFICATE_CATEGORY=CA; CKA_TRUSTED; 
	ID: 

$ openssl req -engine pkcs11 -key "pkcs11:token=00ABC;object=device;type=private " -keyform engine -new -out new_device.csr -subj "/CN=NEW CSR EXAMPLE"
engine "pkcs11" set.
Unknown object type
The key ID is not a valid PKCS#11 URI
The PKCS#11 URI format is defined by RFC7512
Unknown object type
The key ID is not a valid PKCS#11 URI
The PKCS#11 URI format is defined by RFC7512
PKCS11_get_private_key returned NULL
cannot load Private Key from engine
3069767696:error:80065064:pkcs11 engine:ctx_load_key:invalid id:eng_back.c:696:
3069767696:error:26096080:engine routines:ENGINE_load_private_key:failed loading private key:crypto/engine/eng_pkey.c:77:
unable to load Private Key
$ p11tool --export-pubkey --provider /usr/lib/libcryptoauth.so
warning: --login was not specified and it may be required for this operation.
warning: no --outfile was specified and the public key will be printed on screen.
Error in pkcs11_export_pubkey:1397: The requested data were not available.`

**To Reproduce**
linux4sam-2021.04 with cryptoauthlib v3.3.3

**Expected behavior**
Generate a certificate

**Additional context**
v3.2.5 with with 2 extra patches worked just fine on the same machine.

**Comment by bryan-hunt** [comment]
1) Don't try to initialize an already initialized device. You're using a trust part and it comes preconfigured with a different configuration than what initialize tries to program. If it is a trust flex part that could render the stored certificates unusable

2) You have a space at the end of your key string in the openssl command which is why it failing with the RFC1512 URI format error
