### ISSUE TITLE
Issue : talib not found while compile for TA100

### ISSUE THREAD

**Issue by Darsh-Dev** [MicrochipTech/cryptoauthlib#284]
**Describe the bug**
While trying to compile the code, facing with #include "talib/talib_status.h".
Project : serial_number_ta100_sam_e54_xpro I have selected for testing.

**To Reproduce**
1. While building the project from [cryptoauthlib_apps](https://github.com/Microchip-MPLAB-Harmony/cryptoauthlib_apps). facing the issue with **talib library not found** 

**Expected behavior**
>CLEAN SUCCESSFUL (total time: 0ms)
make -f nbproject/Makefile-sam_e54_xpro_ta100.mk SUBPROJECTS= .build-conf
make[1]: Entering directory 'E:/MPLAB-Crypto-Harmony/cryptoauthlib_apps-master/apps/serial_number/firmware/sam_e54_xpro_ta100.X'
make -f nbproject/Makefile-sam_e54_xpro_ta100.mk dist/sam_e54_xpro_ta100/production/sam_e54_xpro_ta100.X.production.hex
make[2]: Entering directory 'E:/MPLAB-Crypto-Harmony/cryptoauthlib_apps-master/apps/serial_number/firmware/sam_e54_xpro_ta100.X'
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_ecdsa.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_ecdsa.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_sw_ecdsa.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1010117788/sha2_routines.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1010117788/sha2_routines.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/hashes/sha2_routines.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_cmac.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_cmac.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_hw_aes_cmac.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_sha1.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_sha1.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_sw_sha1.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1010117788/sha1_routines.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1010117788/sha1_routines.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/hashes/sha1_routines.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_rand.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_rand.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_sw_rand.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_cbc.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_cbc.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_hw_aes_cbc.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_ctr.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_ctr.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_hw_aes_ctr.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_sha2.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_sha2.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_sw_sha2.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
"C:\Program Files\Microchip\xc32\v4.00\bin\xc32-gcc.exe" -g -x c -c -mprocessor=ATSAME54P20A -ffunction-sections -fdata-sections -O1 -fno-common -I"../src" -I"../src/config/sam_e54_xpro_ta100" -I"../src/packs/ATSAME54P20A_DFP" -I"../src/packs/CMSIS/CMSIS/Core/Include" -I"../src/packs/CMSIS/" -I"../src/arm" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib" -I"../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto" -Werror -Wall -MP -MMD -MF "build/sam_e54_xpro_ta100/production/_ext/1845778021/atca_hal.o.d" -o build/sam_e54_xpro_ta100/production/_ext/1845778021/atca_hal.o ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/hal/atca_hal.c -DXPRJ_sam_e54_xpro_ta100=sam_e54_xpro_ta100
nbproject/Makefile-sam_e54_xpro_ta100.mk:508: recipe for target 'build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_cbc.o' failed
In file included from ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_hw_aes_ctr.c:35:
../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/cryptoauthlib.h:111:10: fatal error: talib/talib_status.h: No such file or directory
#include "talib/talib_status.h"
^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_hw_aes_cmac.c:35:
../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/cryptoauthlib.h:111:10: fatal error: talib/talib_status.h: No such file or directory
#include "talib/talib_status.h"
^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_hw_aes_cbc.c:35:
../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/cryptoauthlib.h:111:10: fatal error: talib/talib_status.h: No such file or directory
#include "talib/talib_status.h"
^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_cbc.o] Error 255
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_ctr.o] Error 255
make[2]: *** [build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_cmac.o] Error 255
nbproject/Makefile-sam_e54_xpro_ta100.mk:520: recipe for target 'build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_ctr.o' failed
nbproject/Makefile-sam_e54_xpro_ta100.mk:514: recipe for target 'build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_hw_aes_cmac.o' failed
In file included from ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/hal/atca_hal.c:35:
../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/cryptoauthlib.h:111:10: fatal error: talib/talib_status.h: No such file or directory
#include "talib/talib_status.h"
^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [build/sam_e54_xpro_ta100/production/_ext/1845778021/atca_hal.o] Error 255
In file included from ../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/crypto/atca_crypto_sw_sha2.c:28:
../src/config/sam_e54_xpro_ta100/library/cryptoauthlib/cryptoauthlib.h:111:10: fatal error: talib/talib_status.h: No such file or directory
#include "talib/talib_status.h"
^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_sha2.o] Error 255
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2
nbproject/Makefile-sam_e54_xpro_ta100.mk:550: recipe for target 'build/sam_e54_xpro_ta100/production/_ext/1845778021/atca_hal.o' failed
nbproject/Makefile-sam_e54_xpro_ta100.mk:544: recipe for target 'build/sam_e54_xpro_ta100/production/_ext/1020214353/atca_crypto_sw_sha2.o' failed
make[2]: Leaving directory 'E:/MPLAB-Crypto-Harmony/cryptoauthlib_apps-master/apps/serial_number/firmware/sam_e54_xpro_ta100.X'
nbproject/Makefile-sam_e54_xpro_ta100.mk:91: recipe for target '.build-conf' failed
make[1]: Leaving directory 'E:/MPLAB-Crypto-Harmony/cryptoauthlib_apps-master/apps/serial_number/firmware/sam_e54_xpro_ta100.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed

**Additional context**
Issue is not specific to this repo, however code base is almost similar. **talib** is not able to be found with this [cryptoauthlib](https://github.com/MicrochipTech/cryptoauthlib) as well.

Can you please help, from where I can get the "talib"?

Thanks

**Comment by bryan-hunt** [comment]
You need to send a request though your assigned FAE or account manager. If you have neither you can send a request through the myMicrochip support sytem.
