### ISSUE TITLE
Random number health test fail

### ISSUE THREAD

**Issue by dt-nam** [MicrochipTech/cryptoauthlib#285]
**Describe the bug**
Random number generator locks up and needs a power cycle to recover.
**To Reproduce**
1. Create a utility that requests a random number every 100ms.
I ran mine with "while true ; do  date &&  u608a -r && sleep .10 ; done
"
2. Run the utility for about 12-16 hours
4. See error  random failed... 0xfa (0xfa is health check)

**Expected behavior**
As the i2c linux driver is reinitialized every execution, I would expect that it would recover after internally reinitializing.

**Additional context**
This is running i2c, linux, cryptoauthlib v3.2.2a

**Comment by bryan-hunt** [comment]
This is product question not a library issue. As you've indicated above I2C is operating just fine and it's getting a health check failure back from the device. The datasheet describes the random number generator's health check behavior, configuration settings, and how to clear it and resume operation in detail.

As the issue template points out for product support requests you need to submit a request through the [myMicrochip Support portal](https://microchipsupport.force.com/s/).

For details on the myMicrochip Support Portal or how to use it please see the [instructions for using the myMicrochip Support portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case)
