### ISSUE TITLE
Does `atcacert_create_csr()` return ASN.1 encoder der?

### ISSUE THREAD

**Issue by umanayana** [MicrochipTech/cryptoauthlib#29]
I am having some trouble using atcacert_create_csr(). 
The doxygen states it return `int der`, I've never heard of '`int der` format before, so not sure if that a typo.
So the CSR returned is it ASN.1 encoded?

**Comment by BenUdall-Microchip** [comment]
Yup, "int der" is a typo. It should say DER format, which is the standard binary encoding of ASN.1

**Comment by umanayana** [comment]
It doesn't seem to be encoded in asn.1. when I try to load it into OpenSSL
it fails. The error code relates to incorrect ASN.1 encoding.

If I use the method to convert it to a PEM I can then load it with OpenSSL.
So I think the data is fine but something doesn't seem correct with the
formatting of the der. But the code that converts it to PEM seem to
understand how to read it.

**Comment by bryan-hunt** [comment]
OpenSSL assumes PEM for everything on the command line. When using der you have to use -inform der

**Comment by umanayana** [comment]
That's the command I used. It throws an error related to ASN1 encoding. 
But if I use the method that generate the PEM certificate it can be read my OpenSSL fine. That method doesn't do much expect for convert the existing DER formatted cert to PEM.

I haven't really investigate further, but it may be a bug in the code that generated the DER format, where it's not actually generating DER but the code that goes from DER to PEM is somehow handling it. (I'm making guesses here)
