### ISSUE TITLE
mbedTLS 2.28.0 LTS

### ISSUE THREAD

**Issue by fstephany** [MicrochipTech/cryptoauthlib#292]
Hello, 

We're upgrading a product to the latest mbedTLS LTS branch ([2.28.0](https://github.com/Mbed-TLS/mbedtls/releases/tag/v2.28.0)). Upgrading from the previous LTS (2.16.X) was quite straightforward, we only had to add the `mbedtls_ecdsa_can_do` function. We got inspiration from [a thread on the Microchip forum](https://www.microchip.com/forums/m1181777.aspx) to get started.

Things seems to be running smoothly but is there any other point that we should pay attention to?

**Comment by jd-imi** [comment]
2.28.5 fixed the issue with https://github.com/Mbed-TLS/mbedtls/issues/7498
