### ISSUE TITLE
cryptoauthlib 20220320 macosx arm64 builds are actually x86-64

### ISSUE THREAD

**Issue by robey** [MicrochipTech/cryptoauthlib#297]
**Describe the bug**
The binary wheels for version 20220320, macosx, arm64 are actually built with an x86_64 dylib, not arm64. This is true across the python 3.8, 3.9, and 3.10 releases.

**To Reproduce**
1. Download and unpack one of the wheels -- for example: cryptoauthlib-20220320-cp310-cp310-macosx_11_0_arm64.whl
2. Run: `file cryptoauthlib/libcryptoauth.dylib`
3. Notice it is built for x86_64, not arm64.

**Expected behavior**
A wheel of cryptoauthlib which works on arm64 macosx.

**Additional context**
n/a

**Comment by bryan-hunt** [comment]
This should have been resolved originally in cryptoauthlib==20221018 which now properly shows universal shared libraries for OSX
