### ISSUE TITLE
calib_wakeup_i2c is not thread safe at > 100 kHz

### ISSUE THREAD

**Issue by ewalt1** [MicrochipTech/cryptoauthlib#299]
The implementation of calib_wakeup_i2c performs a bus reconfiguration to 100 kHz, writes to address 0x0, then reconfigures it back to the original clock frequency. This can cause issues if there are other threads using the bus simultaneously. The legacy API was better in this regard since it allowed a custom wake function which could hold a bus lock across the whole sequence or while doing some other trickery with SDA.

Ideally I'd say the API should be modified to allow specifying a custom wake function. A reasonable alternative would be to send the ATCA_HAL_CONTROL_WAKE through the halcontrol function and if it's UNIMPLEMENTED fallback to the existing implementation.

**Comment by bryan-hunt** [comment]
Cryptoauthlib is not threadsafe. You need to lock access before any cryptoauthlib call. Simply locking in the wake will not help system stability. You may have okay success locking in wake and unlocking at the end of idle but it'll still have reliability issues.

There are plans to add safety that will manage this appropriately.
