### ISSUE TITLE
Using Cryptoautlib Python with I2C raspberry

### ISSUE THREAD

**Issue by josepacelli** [MicrochipTech/cryptoauthlib#30]
There is a example that how to use this lib with i2c dev in raspberry?

**Comment by BenUdall-Microchip** [comment]
The closest thing we have right now is a makefile [Makefile.zip](https://github.com/MicrochipTech/cryptoauthlib/files/2350210/Makefile.zip) that builds the unit test project for linux i2c, which works on a raspberry pi.

**Comment by bryan-hunt** [comment]
If you check out the [cryptoauthtools](https://github.com/MicrochipTech/cryptoauthtools/blob/master/python/examples/info.py) repo there are examples for use of the python module - including alternative interfaces such as i2c which is built with cryptoauthlib. The key part is modifying the parameters in configuration structure:

```
cfg = cfg_ateccx08a_i2c_default()
cfg.cfg.atcai2c.bus = 1        # Raspberry Pi I2C bus number
cfg.cfg.atcai2c.slave_address = 0xC0        #I2C address of the part - in the part expected format (left shifted 1 bit)
atcab_init(cfg)
```

For example if your device slave address is 0x58 as probed, that is 0xB0 when shifted so you would use the command:
```
pi@raspberrypi:~ $ python info.py -i i2c -p slave_address=0xB0
```

The slave address is shifted left one bit from what you would see in i2cdetect when you probe the i2c bus:

```
pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- 58 -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
```

**Comment by praveenmuthusamy** [comment]
info.py gives assertion with my rpi4
`root@raspberrypi-cm4:/media# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- 35 -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                        `

`root@raspberrypi-cm4:/media# python3 info.py -i i2c -p slave_address=0x6A
<cryptoauthlib.iface.ATCAIfaceCfg object at 0x7fb008ad40>
Traceback (most recent call last):
  File "info.py", line 95, in <module>
    info(args.iface, args.device, **parse_interface_params(args.params))
  File "info.py", line 47, in info
    assert atcab_init(cfg) == ATCA_SUCCESS
AssertionError
`

**Comment by bryan-hunt** [comment]
@praveenmuthusamy A new version was released that reset the default baud rate on linux to 100khz (which is actually a dummy value as the i2c bus speed is set by devicetree). I would recommend trying out the latest version (20210620). Also on this version of the raspberry pi you might need to set the bus manually:

```
python3 info.py -i i2c -p address=6a bus=1
```

**Comment by praveenmuthusamy** [comment]
@bryan-hunt thanks for your response, it works.
Any idea on how to use ATECC608 as hardware accelerator for dm-crypt decryption?
