### ISSUE TITLE
ATECC608A configuration's bits order

### ISSUE THREAD

**Issue by Embdded-geek** [MicrochipTech/cryptoauthlib#311]
Hello i am working on a project where i need to do my custom configuration for ATECC608A and i need to know how bits are read in two bytes configuration's word are they in little Endian or Big Endian and is bit 0 the weakest bit or the strongest one ?
ps : here the documentation you can look in slotconfig part for example https://atecc608a.neocities.org/ATECC608A.pdf.
Thank you in advance

**Comment by bryan-hunt** [comment]
For product support please submit a request through the [mySupport portal](https://microchipsupport.force.com/s/) where Microchip's global team of FAEs can work on your use case and questions.

For details on the mySupport Portal or how to use it please see the [instructions for using the mySupport portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case)

You have posted a link from a DMCA violating website specifically created to breech the datasheet NDA. We know the content of our datasheets. You will need to go through the support system so the NDA will be verified and you can gain access to the datasheet from the Secure Documents section of the myMicrochip portal.
