### ISSUE TITLE
New PKCS#11 C_Sign does no longer allow empty buffer

### ISSUE THREAD

**Issue by op** [MicrochipTech/cryptoauthlib#315]
You can no longer pass in a NULL for the signature buffer and get back the number of bytes required. This is how the p11tool work too.

```
$ p11tool --provider=/usr/lib/libcryptoauth.so --test-sign 'pkcs11:object=device'
[..]
10:10:C_Sign:623:CKR_ARGUMENTS_BAD(7)
Cannot sign data: The request is invalid.
```

I created #314 to fix this. Cheers!

**Comment by bryan-hunt** [comment]
Resolved in v3.4.1
