### ISSUE TITLE
Does ATECC608B supports I2C 400 000 baudrate ?

### ISSUE THREAD

**Issue by LumbirBwut** [MicrochipTech/cryptoauthlib#318]
Hi, 
I'm actually using an esp32 and communicating with my ATECC608B cryptochip through I2C.
Everything is working fine using standard configuration, however as soon as I increase the baudrate to 400 000, I receive only I2C fail communication with my cryptochip.

Is the baud rate on the bus caped as the following lines of code suggest:
```c
ATCA_STATUS hal_i2c_init(ATCAIface iface, ATCAIfaceCfg *cfg)
{
    esp_err_t rc = ESP_FAIL;
    int bus = cfg->atcai2c.bus;

    if (bus >= 0 && bus < MAX_I2C_BUSES)
    {
        if (0 == i2c_hal_data[bus].ref_ct)
        {
            i2c_hal_data[bus].ref_ct = 1;
            i2c_hal_data[bus].conf.mode = I2C_MODE_MASTER;
            i2c_hal_data[bus].conf.sda_pullup_en = GPIO_PULLUP_DISABLE;
            i2c_hal_data[bus].conf.scl_pullup_en = GPIO_PULLUP_DISABLE;
            i2c_hal_data[bus].conf.master.clk_speed = 100000; //cfg->atcai2c.baud;
```
The last line suggest that user couldn't use the baudrate specified in its I2C configuration.

Is there something I must setup to get it working?

Thanks in advance 👍

**Comment by bryan-hunt** [comment]
Check the copyright at the top of the file. This is not a limitation of the ATECC608B
