### ISSUE TITLE
How to store device certificate in cryptochip ECC608

### ISSUE THREAD

**Issue by amolchor25** [MicrochipTech/cryptoauthlib#323]
Hi
I have to store one certificate in ecc608 chip memory.
I have used p11tool write command to write the certificate in token 00ABC that is ecc608 device token, but it gives an error while executing.
here I have attached screenshot of it.
![Screenshot from 2022-12-21 15-08-03](https://user-images.githubusercontent.com/58142068/208874015-f84bf4b6-b0f4-48e4-a59d-3e38ca763f5f.png)

**Comment by bryan-hunt** [comment]
That is not a supported operation with the ATECC608 device. For custom certificate provisioning please use the [Trust Platform Design Suite](https://www.microchip.com/en-us/product/SW-TPDSV2)
