### ISSUE TITLE
Missing return in atcab_aes_ccm_aad_finish

### ISSUE THREAD

**Issue by peschuster** [MicrochipTech/cryptoauthlib#335]
In https://github.com/MicrochipTech/cryptoauthlib/blob/86b3046d2e0b74af20cf6694ada5cc21af18c0d1/lib/crypto/atca_crypto_hw_aes_ccm.c#L370-L376 pointer 'ctx' is checked for NULL at line 370 but will be dereferenced at line 376.

I think there is a return statement missing or the condition in line 376 should be extended to cover a null pointer.

**Comment by Srinivas-E** [comment]
This has been resolved in latest CAL release versions.
![image](https://github.com/user-attachments/assets/0c584013-aff8-4a8f-9ee3-1bdfde900778)

**Comment by Srinivas-E** [comment]
Addressed

**Comment by Srinivas-E** [comment]
Addressed
