### ISSUE TITLE
pkcs11 branch is missing

### ISSUE THREAD

**Issue by 0xaaa111** [MicrochipTech/cryptoauthlib#344]
**Describe the bug**

According to the [cryptoauthlib-manual.pdf](https://github.com/MicrochipTech/cryptoauthlib/blob/main/cryptoauthlib-manual.pdf) , PKCS support is implemented on branch **pkcs11**. But this branch is not presented in repository.

**To Reproduce**
1.See cryptoauthlib-manual.pdf page 12
2.git clone --single-branch -b pkcs11 https://github.com/MicrochipTech/cryptoauthlib
3.cloning fails "fatal: Remote branch pkcs11 not found in upstream origin"

**Expected behavior**
![image](https://github.com/MicrochipTech/cryptoauthlib/assets/139857172/b8eae73c-b984-4498-832d-5ee36ea4a2bd)

**Comment by bryan-hunt** [comment]
PKCS11 is a mainline feature that is simply enabled with the cmake option `ATCA_PKCS11`. Please see the wiki: https://github.com/MicrochipTech/cryptoauthlib/wiki/PKCS11

We'll update the doc generation.

**Comment by 0xaaa111** [comment]
@bryan-hunt Thank you
