### ISSUE TITLE
i2c read returns error: 0xF0: ATCA_COMM_FAIL and 0xF5 : ATCA_UNIMPLEMENTED

### ISSUE THREAD

**Issue by RoboAsystent** [MicrochipTech/cryptoauthlib#359]
Hi,
I'm trying to integrate ATECC608B module into Yocto Linux 5.15 running on RPi CM4. I tried to communicate with module using i2c by direct calls of cryptoauth library (v3.2.x) and pkcs11 interface (libp11 ver. 0.4.11) to generate random number and read serial number. Direct API source code used:

```
uint8_t buff[32];
uint8_t serial[9];
atcab_init(&cfg_ateccx08a_i2c_default);
atcab_random(buff);
atcab_read_serial_number(serial);
// prints random and serial
atcab_release();
```
This example produces following errors:
Atcontrol : status: 0xF5
calib_wakeup_i2c : status: 0xF5
Awaking i2c ... : status: 0xF5
calib_wakeup : status: 0xF5
calib_execute_send : status: 0xF0
Execution command status: 0xF0
cryptoauthlib/lib/calib/calib_read.c:103:f0:calib_read_zone - execution failed
cryptoauthlib/lib/calib/calib_read.c:619:f0:calib_read_zone - falied
i2c read error: : Remote I/O error
Atreceive : status: 0xF0

Module is attached to i2c bus 1 with 400000 baud rate, I tried it with 100k as well, still same issue. I changed cfg_ateccx08a_i2c_default too. However random number seems to be fine but serial number changes every time I execute it.

Example output:
Random number: 10 92 BF CD 7F 00 00 00 5C 9C 40 00 00 00 00 00 03 00 00 00 00 00 00 00 E0 CA 97 2D 00 00 00 00 
Serial number : E8 92 BF CD 7F 00 00 00 10

And another execution:
Random number : 60 B9 47 D7 7F 00 00 00 5C 9C 40 00 00 00 00 00 03 00 00 00 00 00 00 00 E0 FA 34 06 00 00 00 00 
Serial number : 38 BA 47 D7 7F 00 00 00 10

It seems like it can't properly read back data from module. What is more, when I used pkcs11 interface to do the same I had following output:

1 slots available
Slot manufacturer......: Microchip Technology Inc
Slot description.......: 0_3_0
Slot token label.......: 00ABC
Slot token manufacturer: Microchip Technology Inc
Slot token model.......: ATECC608A
Slot token serialnr....: 239CEAEA018096EE

Random number : FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00 FF FF 00 00

I used this simple example code: https://github.com/OpenSC/libp11/blob/master/examples/getrandom.c
I found on forum that this strange output for random number call is related to lock of configuration zone: https://forum.microchip.com/s/topic/a5CV40000000EcTMAU/t393713

I tried to find answer how to properly configure it for Linux and what I found didn't help. Can anyone give me a hint what might be a problem or if there is a configuration step that I'm missing and is causing this issue?

**Comment by Srinivas-E** [comment]
Hi,
Can you pls raise a [support ticket](https://microchip.my.site.com/s/supportservice/) for this query?
