### ISSUE TITLE
Help to install with `pip install`

### ISSUE THREAD

**Issue by NSLog0** [MicrochipTech/cryptoauthlib#36]
I ran pip install then I got an error. How should I fix it
<img width="1568" alt="screen shot 2018-09-22 at 12 39 16 pm" src="https://user-images.githubusercontent.com/1640817/45913822-ab046880-be64-11e8-82d2-83994b52d132.png">

Info: 
Python 3.5.5

**Comment by NSLog0** [comment]
Thank you, For you supporting. 

It looks like an option that you prefer didn't work

**Comment by NSLog0** [comment]
@bryan-hunt Hi, I'm still waiting for your support, if you have the alternative way to use ATEC chip with python, can you suggest while you're working with an issue

**Comment by NSLog0** [comment]
@BenUdall-Microchip I'm haven't tried a new version yet, but I tried your current version with RPi model 3 is not working too. I will capture error after I on may laptop

**Comment by NSLog0** [comment]
@BenUdall-Microchip Have you update a version yet?, Please remind me after you finished

**Comment by bryan-hunt** [comment]
@NSLog0 A new version was released last week that should resolve most issues. Make sure to use the `--upgrade` option when using pip.
