### ISSUE TITLE
Integrating CryptoAuthLib with MilkV Duo for ATECC608A: Seeking Clarification on Configuration and HAL Implementation

### ISSUE THREAD

**Issue by taspenwall** [MicrochipTech/cryptoauthlib#360]
I'm just a hobbyist and I'm eager to learn more about the ATECC608 security chip. Although I'm relatively new to programming, I'm picking things up quickly. I'm currently facing some issues with CryptoAuthLib on a MilkV Duo RISC-V 64 dev board (apologies if this isn't the appropriate place to post). My MilkV Duo supports Linux and includes Linux user-space I2C support, so I'm looking to utilize the I2C Linux user-space HAL. I managed to cross-compile CryptoAuthLib and set the ATCA_HAL_I2C compiler flag during the build. However, I'm unsure how to specify the use of the hal_linux_i2c_userspace HAL. Is this configuration done within my program or at the library's compile time? I haven't found any compiler flags that allow for the specification of the HAL beyond ATCA_HAL_I2C. On the programming side, I'm struggling to find examples that demonstrate how to select the HAL, leaving me somewhat confused.

Additionally, I'm having difficulty finding documentation that explains how to set configurations for the key slots and keys. I understand that these settings are applied by writing to the config zone, but decoding this configuration zone is beyond my current understanding. I found a spec sheet for the ATECC608A-TNGLTLS, which comes with preconfigured slots, but it only provides config values for those specific configurations. Are there comprehensive documents that describe this process? Are they possibly restricted under NDA requirements? I've requested access to the full data sheet but have been denied access to it as im not a corprate customer. Thanks for any guidance you can provide.

Tom

**Comment by Srinivas-E** [comment]
Thank you for using Microchip Security Products and reporting the observation. Please submit a request through the [myMicrochip Support portal](https://microchipsupport.force.com/s/). For details on the myMicrochip Support Portal or how to use it please see the [instructions for using the myMicrochip Support portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case).
