### ISSUE TITLE
library not compatible with current zephyr rtos version

### ISSUE THREAD

**Issue by maass-hamburg** [MicrochipTech/cryptoauthlib#364]
**Describe the bug**
Due to changes in zephyr rtos, header files have changed. 
This library can not be used with the current zephyr version.

**To Reproduce**
1. include this library to a zephyr app
2. Build the app
3. See error

**Expected behavior**
Build should not fail.

**Additional context**
A attempt hat been previded in https://github.com/MicrochipTech/cryptoauthlib/pull/355, but that got closed.

**Comment by KalyanCManukonda** [comment]
Thank you for using Microchip Security Products and reporting the observation. Please submit a request through the [myMicrochip Support portal](https://microchipsupport.force.com/s/). For details on the myMicrochip Support Portal or how to use it please see the [instructions for using the myMicrochip Support portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case).
