### ISSUE TITLE
add configuration to use this library as zephyr module

### ISSUE THREAD

**Issue by maass-hamburg** [MicrochipTech/cryptoauthlib#365]
**Describe the solution you'd like**
This library should be able to be used as a zephyr module as described in https://docs.zephyrproject.org/latest/develop/modules.html#using-west. It should provide the necessary files to be automatically included. Preferably by adding a `zephyr` folder in the root and having `zephyr/module.yml`, `zephyr/CMakeLists.txt` and `zephyr/Kconfig` there.   

**Describe alternatives you've considered**
The user has to implement it themself, as statted in https://github.com/MicrochipTech/cryptoauthlib/issues/275   

**Additional context**

**Comment by KalyanCManukonda** [comment]
Thank you for using Microchip Security Products and reporting the observation. Please submit a request through the [myMicrochip Support portal](https://microchipsupport.force.com/s/). For details on the myMicrochip Support Portal or how to use it please see the [instructions for using the myMicrochip Support portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case).
