### ISSUE TITLE
Python library load error 

### ISSUE THREAD

**Issue by adelmiljkovic** [MicrochipTech/cryptoauthlib#366]
When I try any of the examples I get "Unable to find cryptoauthlib. You may need to reinstall". I have installed it using the pip command into a virtual environment on a Raspberry Pi 4. 

I'm using the ATSHA204A over I2C and it's detected by the Pi. The library seems to be installed as I see it with `pip list` but for some reason load_cryptoauthlib() throws LibraryLoadError.

**Comment by KalyanCManukonda** [comment]
Thank you for using Microchip Security Products and reporting the observation. Please submit a request through the [myMicrochip Support portal](https://microchipsupport.force.com/s/). For details on the myMicrochip Support Portal or how to use it please see the [instructions for using the myMicrochip Support portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case).
