### ISSUE TITLE
ATCA_SLOT_CONFIG_GEN_KEY_SHIFT and ATCA_SLOT_CONFIG_PRIV_WRITE_SHIFT

### ISSUE THREAD

**Issue by electronicayciencia** [MicrochipTech/cryptoauthlib#367]
Hello.

I have a question about these constants:
https://github.com/MicrochipTech/cryptoauthlib/blob/9a5b711582b3df0ed97fa6147c899eb856c52d34/lib/calib/calib_device.h#L192-L195

According to ATECC508 datasheet:
- Table 2-10. Write Configuration Bits: GenKey Command (bit 13)
- Table 2-11. Write Configuration Bits: PrivWrite Command (bit 14)

Shouldn't be that constants 13 and 14?

I didn't use these devices before, so maybe I am wrong.  

Thank you.

**Comment by elesmera11** [comment]
+1, this issue still exists, assuming it is an issue
