### ISSUE TITLE
Set ABI version in the shared library

### ISSUE THREAD

**Issue by smanni** [MicrochipTech/cryptoauthlib#373]
**Describe the solution you'd like**
ABI version is missing in the shared library.

`readelf -d lib/libcryptoauth.so | grep SONAME
 0x0000000e (SONAME)                     Library soname: [libcryptoauth.so]
`

should be:

`readelf -d lib/libcryptoauth.so | grep SONAME
 0x0000000e (SONAME)                     Library soname: [libcryptoauth.so.3]
`

note .3 at the end.

**Describe alternatives you've considered**
No alternatives.

**Additional context**
It can be easily set in CMAKE. Read here: https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html

**Comment by Srinivas-E** [comment]
Hi @smanni ,
Thank you for reaching us with your feedback.
We shall incorporate this change into our upcoming release cycle
