### ISSUE TITLE
Error in pkcs11_export_pubkey:1397: The requested PKCS #11 object is not available

### ISSUE THREAD

**Issue by Anzal-calixto** [MicrochipTech/cryptoauthlib#382]
i am having issues in setting up pkcs#11 . The Development board i am using is DM20118 (atecc608b) with a raspberrypi. what is possibly wrong here can anybody help
```

warning: --login was not specified and it may be required for this operation.
warning: no --outfile was specified and the public key will be printed on screen.
Error in pkcs11_export_pubkey:1397: The requested PKCS #11 object is not available


```

**Comment by Srinivas-E** [comment]
Hi @Anzal-calixto 
Thank you for reaching us. You may create a support ticket at [myMicrochip Support portal](https://microchipsupport.force.com/s/) to get assistance on this item.

For details on the myMicrochip Support Portal or how to use it please see the [instructions for using the myMicrochip Support portal](https://microchipsupport.force.com/s/article/How-to-submit-a-case).

Regards,
Srinivas
