### ISSUE TITLE
Repository contains CRLF line endings

### ISSUE THREAD

**Issue by vgottardi** [MicrochipTech/cryptoauthlib#47]
The CRLF line endings create issues when working in Linux and OS X.
https://help.github.com/articles/dealing-with-line-endings/

**Comment by bryan-hunt** [comment]
Yes, some of our style enforcement tools need to be updated. While we do currently build on travis.ci for linux and osx it is a specialized use case. Which tool are you experiencing trouble with?

**Comment by vgottardi** [comment]
I'm getting issues making a yocto patch:
patching file lib/hal/hal_linux_i2c_userspace.c
Hunk #1 FAILED at 40 (different line endings).

**Comment by bryan-hunt** [comment]
This should be resolved by f86b9db

**Comment by vgottardi** [comment]
Great, however I'm using the pkcs11 branch. Will there be a merge soon (from master to pkcs11 or the other way around)?

**Comment by bryan-hunt** [comment]
This should have been resolved with the mainlining of pkcs11. I'm closing this ticket as being stale.
