### ISSUE TITLE
ATECC608A actab_random returns strange results

### ISSUE THREAD

**Issue by AFellmett** [MicrochipTech/cryptoauthlib#51]
I'm working on ESP8266 with new RTOS SDK v3.1 and use the ATECC608A.
With v3.1 the i2c interface is very similar to ESP32 so I'm using the hal_esp32_i2c.

It's working as expected, I'm able to wake up the the chip and also the actab_random() function returns valid results. 
But the returned data are always the same and seems to be wrong: 8 times `0xff 0xff 0x00 0x00`

Below I added some log messages (Except the 'Received Dump' I used the existing commented comments from hal_esp32_i2c

_**atcab_init()** - default settings except: I2C Bus = I2C_NUM_0 && devtype = ATECC608A_
I (602) HAL_I2C: Configuring I2C
D (602) HAL_I2C: I2C Driver Install; 0
D (622) HAL_I2C: I2C Param Config: 0
D (652) HAL_I2C: Received 4 bytes - Dump: 
0x04 0x11 0x33 0x43 
I (652) HAL_I2C: I2C wake successful
D (652) HAL_I2C: txdata: 0x3fff3720 , txlength: 8
D (672) HAL_I2C: Received 35 bytes - Dump: 
0x23  0x01 0x23 0x88  0x05  0x00  0x00 0x60  0x02 0x81 0x97 0xba 0xf6 0xee  0x01 0x5d  0x00 0xc0  0x00  0x00  0x00 0x83 0x20 0x87 0x20 0x8f 0x20 0xc4 0x8f 0x8f 0x8f 0x8f 0x8f 0x90 0xa8 
I (682) HAL_I2C: IDLE Command Sent

_**atcab_buffer()** - returns always the same_
D (712) HAL_I2C: Received 4 bytes - Dump: 
0x04 0x11 0x33 0x43 
I (712) HAL_I2C: I2C wake successful
D (712) HAL_I2C: txdata: 0x3fff37b0 , txlength: 8
D (732) HAL_I2C: Received 35 bytes - Dump: 
0x23 0xff 0xff 0x00 0x00 0xff 0xff 0x00 0x00 0xff 0xff 0x0 0x00 0xff 0xff 0x00 0x00 0xff 0xff 0x00 0x00 0xff 0xff 0x00 0x00 0xff 0xff 0x00 0x00 0xff 0xff 0x0 0x0 0x41 0x1a 
I (742) HAL_I2C: IDLE Command Sent

**Comment by bryan-hunt** [comment]
This is the test pattern output from the RNG prior to the configuration being locked. Details can be found in the datasheet [ATECC508A](http://ww1.microchip.com/downloads/en/DeviceDoc/20005927A.pdf) in section 3.3.2 where it defines RNG behavior.

**Comment by AFellmett** [comment]
Thanks for the fast answer, I had a look for this specific pattern but I didn't found it
