### ISSUE TITLE
atcab_sha fails at a size of over 4kb

### ISSUE THREAD

**Issue by habebit** [MicrochipTech/cryptoauthlib#60]
Is there a data size limitation for the atecc508a for hashing data? I've tested multiple data sizes and at a data size of over 4kb I get the `ATCA_GEN_FAIL= 0xE1, //!< unspecified error` error. I use the `atcab_sha` command.

Thank you very much
Habebit

**Comment by BenUdall-Microchip** [comment]
Hi @habebit, I attempted to reproduce your error, but wasn't able to. I successfully hashed messages up to 1MB in size.

**Comment by habebit** [comment]
@BenUdall-Microchip Thanks for your attemp. I use the atecc508a chip on a stm32 f767zi nucleo board via i2c connection. The strange part is that the atecc508a sometimes returns hashed messages up to 4096 Byte, but almost everytime it refuses it and I get the `0xE1` error. Maybe it's a limitation from the stm32 nucleo board. Thanks anyway.
