### ISSUE TITLE
Additional HAL support.

### ISSUE THREAD

**Issue by RealityVoid** [MicrochipTech/cryptoauthlib#63]
Hello,

So I'm working with STM32 MCU's and doing some HAL for those for a project of mine. I guess you're not interested in adding HAL from competing HW vendors yourself, but would you be open to PR's from the community where we add additional HAL's?

**Comment by habebit** [comment]
Can you provide you abstraction layer of your stm32 board? I'm currently working on a stm32 project with an atecc508a chip. But the wake command isn't working as expected.

**Comment by schielimicrochip** [comment]
We typically provide implementations of abstraction layers for the Microchip Microcontrollers but not for those from our competitors. The example implementations should be of food help to “plug” i2c drivers from STM into the HAL

________________________________

**Comment by RealityVoid** [comment]
@habebit I'm still working on it, and you might be further down the road with the HAL than I am. I just have some stupid things happening in my system right now and it's not working right yet. I was kind f hoping I'd find one somewhere, since there obviously are other people who need this.

@schielimicrochip I figured as much, but my question was - if I fork it and do the HAL in my fork would you be open on accepting PR's for these additional HALS? Or considering how they are your competitors you want no such things in your repo?

If I'm going there, I would like to know more about your license terms too, since it says this library should only be used with Microchip products. Do you consider using the atecc chips as sufficient to satisfy the terms of the license or would it be infringement to use this code on another vendor's MCU's?

**Comment by RealityVoid** [comment]
@habebit so, I managed to take a look and I wake up the chip  properly usng the stm32 api. I now have write & read, wakeup and Idle, but it's still janky

my wakeup looks like this:

```
ATCA_STATUS hal_i2c_wake(ATCAIface iface)
{
    ATCAIfaceCfg *cfg = atgetifacecfg(iface);
    int retries = cfg->rx_retries;
    int status = HAL_ERROR;
    uint8_t data[4];

    // Send the 00 address as the wake pulse
    // part will NACK, so don't check for status
	HAL_I2C_Master_Transmit(&hi2c2, 0x00 ,data , 0, 100);

    // wait tWHI + tWLO which is configured based on device type and configuration structure
    atca_delay_ms(2);

    while (retries-- > 0 && status != HAL_OK)
    {
        status = HAL_I2C_Master_Receive(&hi2c2, cfg->atcai2c.slave_address, data, 4, 100);
    }

    if ((status != HAL_OK) && (status != HAL_TIMEOUT))
    {
        return ATCA_COMM_FAIL;
    }

    return hal_check_wake(data, 4);
	return ATCA_SUCCESS;
}
```

**Comment by schielimicrochip** [comment]
We are not opposed to having such HAL in our repo. The main question is always how to support clients that would be using it. If it is pulled into our repo, we need to have evidence it went through proper testing.
Regarding the license, it is pretty straightforward: as soon as you are using this library with at least the CryptoAuthentication device, you meet the licensing requirements. It does not have to be the MCU.

**Comment by SameerChilmattur** [comment]
> @habebit so, I managed to take a look and I wake up the chip properly usng the stm32 api. I now have write & read, wakeup and Idle, but it's still janky
> 
> my wakeup looks like this:
> 
> ```
> ATCA_STATUS hal_i2c_wake(ATCAIface iface)
> {
>     ATCAIfaceCfg *cfg = atgetifacecfg(iface);
>     int retries = cfg->rx_retries;
>     int status = HAL_ERROR;
>     uint8_t data[4];
> 
>     // Send the 00 address as the wake pulse
>     // part will NACK, so don't check for status
> 	HAL_I2C_Master_Transmit(&hi2c2, 0x00 ,data , 0, 100);
> 
>     // wait tWHI + tWLO which is configured based on device type and configuration structure
>     atca_delay_ms(2);
> 
>     while (retries-- > 0 && status != HAL_OK)
>     {
>         status = HAL_I2C_Master_Receive(&hi2c2, cfg->atcai2c.slave_address, data, 4, 100);
>     }
> 
>     if ((status != HAL_OK) && (status != HAL_TIMEOUT))
>     {
>         return ATCA_COMM_FAIL;
>     }
> 
>     return hal_check_wake(data, 4);
> 	return ATCA_SUCCESS;
> }
> ```

having trouble with flaky i2c from stm32 to 508a. Does the 508a have timing constraints on wake cmd? 
on a side note, those 2 return statements are interesting :)

**Comment by RealityVoid** [comment]
I did the thing I had to do with cryptauthlib on STM32 quite a while ago so my memory is hazy. I do remember that indeed, there were some timing constraints related to the wake up, but that depends to the configuration you're loading. 

I did manage to get the HAL to fully comply to what I wanted to do. And I added some other changes. Butthen it just lost interest in it so I omitted to put it on GitHub. I'll see later this evening if I can still find the latest thing I used and maybe I'll put my branch here, who knows maybe some people will find it useful somehow. 

Heh, yes, the 2x return statement was just me being stupid.

**Comment by bullitmaster** [comment]
Hi!

I would like to know if there are plans to add third-party HAL support?
I have a gpio and uart stm32 driver using stm32 HAL. Supporting (F4 and F7 series). Now I am testing them, and soon I am ready to push them out. BUT at the moment, without making changes to the library, compiling them is difficult!
Can you give me advice on how i can builsd it now without making changes?

Best Regards,
bullitmaster!

**Comment by bullitmaster** [comment]
Supporting F4xx, F7xx and H7 series.

**Comment by SenZCS** [comment]
Hi, I am trying to interface ATECC608B with STM32 using cryptoauthlib. How do I map the I2C of STM32 in the cryptoauthlib?

**Comment by bkkrunal** [comment]
Hi @RealityVoid 
I have successfully compiled the library with my stm32 HW and now I have been trying very hard to wakeup ATECC608 using this library. However it just doesn't seem to be waking up and it doesn't respond with wakeup data.
Any chance you have got this working on your HW.
I would highly appreciate your help.

Thanks.

**Comment by dnssoftware** [comment]
> @habebit so, I managed to take a look and I wake up the chip properly usng the stm32 api. I now have write & read, wakeup and Idle, but it's still janky
> 
> my wakeup looks like this:
> 
> ```
> ATCA_STATUS hal_i2c_wake(ATCAIface iface)
> {
>     ATCAIfaceCfg *cfg = atgetifacecfg(iface);
>     int retries = cfg->rx_retries;
>     int status = HAL_ERROR;
>     uint8_t data[4];
> 
>     // Send the 00 address as the wake pulse
>     // part will NACK, so don't check for status
> 	HAL_I2C_Master_Transmit(&hi2c2, 0x00 ,data , 0, 100);
> 
>     // wait tWHI + tWLO which is configured based on device type and configuration structure
>     atca_delay_ms(2);
> 
>     while (retries-- > 0 && status != HAL_OK)
>     {
>         status = HAL_I2C_Master_Receive(&hi2c2, cfg->atcai2c.slave_address, data, 4, 100);
>     }
> 
>     if ((status != HAL_OK) && (status != HAL_TIMEOUT))
>     {
>         return ATCA_COMM_FAIL;
>     }
> 
>     return hal_check_wake(data, 4);
> 	return ATCA_SUCCESS;
> }
> ```

I have tried this and I don't understand why, it doesn't wake up my ATECC608B.
Has anyone got a full sample project or other pointers?

Using STM32G4 chip.

The same hardware is being woken up by an arduino build, which is not what I'd like to use.

**Comment by RealityVoid** [comment]
@dnssoftware  it's been an _eternity_ since I saw one of those chips, so take this with a grain of salt, but I might have a couple of hints: 

- Check your tWHI  configurations, depending on that you might want to wait a bit longer to check the response from slave. 
- I noticed I stupidly did not init data array, try doing that, I don't remember if the wakeup request was just 00 address or the data after was needed as well to be zero. 
- if you're breaking somewhere with a jtag debugger, do be careful, it might throw you back into sleep before you resume and you might _think_ it did not work, when it actually did. 
- Worst case, put a logic analyser on the I2C bus and see what's going on there. 

Sorry I can't help more.

Best,
Vlad R.

**Comment by rikilshah** [comment]
> > @habebit so, I managed to take a look and I wake up the chip properly usng the stm32 api. I now have write & read, wakeup and Idle, but it's still janky
> > my wakeup looks like this:
> > ```
> > ATCA_STATUS hal_i2c_wake(ATCAIface iface)
> > {
> >     ATCAIfaceCfg *cfg = atgetifacecfg(iface);
> >     int retries = cfg->rx_retries;
> >     int status = HAL_ERROR;
> >     uint8_t data[4];
> > 
> >     // Send the 00 address as the wake pulse
> >     // part will NACK, so don't check for status
> > 	HAL_I2C_Master_Transmit(&hi2c2, 0x00 ,data , 0, 100);
> > 
> >     // wait tWHI + tWLO which is configured based on device type and configuration structure
> >     atca_delay_ms(2);
> > 
> >     while (retries-- > 0 && status != HAL_OK)
> >     {
> >         status = HAL_I2C_Master_Receive(&hi2c2, cfg->atcai2c.slave_address, data, 4, 100);
> >     }
> > 
> >     if ((status != HAL_OK) && (status != HAL_TIMEOUT))
> >     {
> >         return ATCA_COMM_FAIL;
> >     }
> > 
> >     return hal_check_wake(data, 4);
> > 	return ATCA_SUCCESS;
> > }
> > ```
> 
> I have tried this and I don't understand why, it doesn't wake up my ATECC608B. Has anyone got a full sample project or other pointers?
> 
> Using STM32G4 chip.
> 
> The same hardware is being woken up by an arduino build, which is not what I'd like to use.

I am currently working on this Chip and initially, I also faced the issue of not getting any response. What helped me was to set I2C bus frequency to 100khz. 

If anyone has done any work on STM32+ATECC608a, I would be interested to know further details.

**Comment by MAD-Riccardo** [comment]
Io ho lavorato e sto lavorando con stm32F7 e H7 e con ATECC508A e ATECC608A.
Se qualcuno avesse bisogno di supporto mi scriva.

**Comment by FaustoYair** [comment]
> Io ho lavorato e sto lavorando con stm32F7 e H7 e con ATECC508A e ATECC608A. Se qualcuno avesse bisogno di supporto mi scriva.

Hi MAD-Ricaardo, how can I contact you? I'm also working but I've had problems using the library.

**Comment by MAD-Riccardo** [comment]
g.riccardo@madengineeringsrl.it
