### ISSUE TITLE
AES-CCM support for ATECC608A

### ISSUE THREAD

**Issue by DurandA** [MicrochipTech/cryptoauthlib#69]
The [ATECC608A product description](https://www.microchip.com/wwwproducts/en/ATECC608A) mentions AES-CCM. However, I don't see any `atcab_aes_ccm*` function. Do you plan to support AES-CCM in *CryptoAuthLib*?

**Comment by BenUdall-Microchip** [comment]
Hi @DurandA , I think that's actually a typo on the page. Should probably say AES-GCM. Either way, the device does support the AES128 ECB and CryptoAuthLib implements a number of block cipher modes around that. Currently we support CBC, CTR, and GCM. CCM is in the works, but not ready yet.

**Comment by DurandA** [comment]
Do you mean that ATECC608A has hardware support for AES-CCM and that you will add software support for it? Or will Microchip release a new device?

Le ven. 22 mars 2019 à 19:48, Ben Udall <notifications@github.com<mailto:notifications@github.com>> a écrit :

Hi @DurandA<https://github.com/DurandA> , I think that's actually a typo on the page. Should probably say AES-GCM. Either way, the device does support the AES128 ECB and CryptoAuthLib implements a number of block cipher modes around that. Currently we support CBC, CTR, and GCM. CCM is in the works, but not ready yet.

**Comment by BenUdall-Microchip** [comment]
ATECC608A has hardware support for AES-ECB, which will be used by a software implementation of CCM in CryptoAuthLib.  Just requires a software/CryptoAuthLib update.

**Comment by DurandA** [comment]
Awesome! Do you have any ETA of AES-CCM support?

**Comment by DurandA** [comment]
Is this still on track?

**Comment by DurandA** [comment]
@BenUdall-Microchip @bryan-hunt I just saw that Microchip released ATECC608A-TNGLORA. LoRaWAN requires AES-CCM and AES-CMAC, is there any LoRaWAN stack available using CryptoAuthLib?

**Comment by schielimicrochip** [comment]
Yes, Microchip has a loRaWAN stack running on the SAMR34 for instance that is using cryptoauthlib. Similarly, ARM has integrated it into their LoRAWAN stack that is part of the mbed stack

Regards
Nicolas Schieli
438 505-3591
________________________________

**Comment by DurandA** [comment]
@schielimicrochip Could you upstream the AES-CCM (and CMAC) implementation from the SAMR34 LoRaWAN stack to CryptoAuthLib?

**Comment by bryan-hunt** [comment]
CCM and CMAC support were added quite a while ago (v3.2.5) but this issue had never been updated.
