### ISSUE TITLE
In linux build, if HID off, don't require udev

### ISSUE THREAD

**Issue by jonsmirl** [MicrochipTech/cryptoauthlib#71]
udev libraries may not be present on embedded systems using i2c
<pre>
diff --git a/lib/CMakeLists.txt b/lib/CMakeLists.txt
index 2d39252..3346d0b 100644
--- a/lib/CMakeLists.txt
+++ b/lib/CMakeLists.txt
@@ -77,9 +77,9 @@ find_library(CORE_LIB CoreFoundation)
 target_link_libraries(cryptoauth ${IO_KIT_LIB} ${CORE_LIB})
 elseif(UNIX)
 if(HAS_LIBUSB)
-target_link_libraries(cryptoauth usb-1.0)
+target_link_libraries(cryptoauth udev usb-1.0)
 endif()
-target_link_libraries(cryptoauth udev rt)
+target_link_libraries(cryptoauth rt)
 endif()
</pre>

**Comment by bryan-hunt** [comment]
This specific requirement should be resolved fully in the latest release.
