### ISSUE TITLE
ESP32 HAL driver

### ISSUE THREAD

**Issue by bugabuga64** [MicrochipTech/cryptoauthlib#76]
Hi, 

Do you guys have the HAL driver for the ESP32 and/or ESP8266 ? 
It couldn't be find in the current version of the documentation. 

Thanks

**Comment by bryan-hunt** [comment]
Yes. See #28 for details of how to use with your platform

The files for the HAL are:
https://github.com/MicrochipTech/cryptoauthlib/blob/master/lib/hal/hal_esp32_i2c.c
https://github.com/MicrochipTech/cryptoauthlib/blob/master/lib/hal/hal_esp32_timer.c

**Comment by bugabuga64** [comment]
Thanks
